twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
        - 'bootstrap_4_layout.html.twig'
        - 'form/fields.html.twig'
    globals:
        siret: '%env(resolve:SIRET)%'
        secu: '%env(resolve:SECU)%'
        version: '%env(resolve:VERSION)%'
