- name: Create frontend directories
  file:
    path: "{{ app_directory }}/frontend/{{ item }}"
    state: directory
    owner: "{{ maintainer_user }}"
    group: "{{ maintainer_user }}"
    mode: '755'
  loop:
    - 'dist'
    - 'log'

- name: Deploy frontend dist
  synchronize:
    delete: true
    src: '{{ playbook_dir }}/../../frontend/{{ item }}'
    dest: "{{ app_directory }}/frontend/"
    recursive: true
    rsync_opts:
      - "--chown={{ maintainer_user }}:{{ maintainer_user }}"
      - '--chmod=0755'
  loop:
    - 'dist'
