# See the configuration reference at https://symfony.com/bundles/SchebTwoFactorBundle/6.x/configuration.html
scheb_two_factor:
    security_tokens:
        - Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken
        - Symfony\Component\Security\Http\Authenticator\Token\PostAuthenticationToken

    totp:
        enabled: true
        server_name: ae2.mp3000.fr      # Server name used in QR code
        issuer: MP3000 Auto Entreprise  # Issuer name used in QR code
#        leeway: 0                      # Acceptable time drift in seconds, must be less or equal than the TOTP period
#        parameters:                    # Additional parameters added in the QR code
#            image: 'https://my-service/img/logo.png'
