# todo build and host images
- name: Deploy docker directories
  synchronize:
    delete: true
    src: '{{ playbook_dir }}/../docker/{{ item }}'
    dest: "{{ app_directory }}/docker/"
    recursive: true
    rsync_opts:
      - "--chown={{ maintainer_user }}:{{ maintainer_user }}"
      - '--chmod=0750'
      - '--exclude=db'
      - '--exclude=log'
  loop:
    - 'backend'
    - 'mariadb'

- name: Create .env and docker-compose.yml
  template:
    src: "templates/{{ item }}.j2"
    dest: "{{ app_directory }}/docker/{{ item }}"
    owner: "{{ maintainer_user }}"
    group: "{{ maintainer_user }}"
    mode: '640'
  loop:
    - '.env'
    - 'docker-compose.yml'

- name: Deploy docker files
  copy:
    src: '{{ playbook_dir }}/../docker/{{ item }}'
    dest: "{{ app_directory }}/docker/"
    owner: "{{ maintainer_user }}"
    group: "{{ maintainer_user }}"
    mode: '640'
  loop:
    - '.dockerignore'
