- name: Create .env.local
  template:
    src: template/.env.local.j2
    dest: "/{{ app_directory }}/.env.local"
    owner: "{{ maintainer_user }}"
    group: "{{ maintainer_user }}"
    mode: '755'

- name: Composer install
  shell:
    cmd: docker-compose exec php_apache bash -l -c "composer install"
    chdir: "{{ app_directory }}"

- name: Composer cache clear
  shell:
    cmd: docker-compose exec php_apache bash -l -c "php bin/console cache:clear"
    chdir: "{{ app_directory }}"

- name: Composer migration
  shell:
    cmd: docker-compose exec php_apache bash -l -c "php bin/console doctrine:migration:migrate --no-interaction"
    chdir: "{{ app_directory }}"

# todo only first time
#- name: Composer fixtures
#  shell:
#    cmd: docker-compose exec php_apache bash -l -c "php bin/console doctrine:fixtures:load -e dev"
#    chdir: "{{ app_directory }}"
