name: backend
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        working-directory: ./backend
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: ctype, iconv, mbstring, mysql
          tools: composer:v2
          coverage: none

      - name: Install Dependencies
        working-directory: ./backend
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dis

      - name: PHP cs fixer
        working-directory: ./backend
        run: composer cs

      - name: PHPStan
        working-directory: ./backend
        run: composer ps

  tests:
    runs-on: ubuntu-latest
    needs: [lint]

    services:
      mariadb_test:
        image: mariadb:10.9
        env:
          MYSQL_ROOT_PASSWORD: secret
          MYSQL_USER: user1
          MYSQL_PASSWORD: password1
          MYSQL_DATABASE: auto_entreprise_test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        working-directory: ./backend
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: ctype, iconv, mbstring, mysql
          tools: composer:v2
          coverage: xdebug

      - name: Install Dependencies
        working-directory: ./backend
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dis

      - name: Create database
        working-directory: ./backend
        run: php bin/console doc:database:create --no-interaction -e test

      - name: Migrate database
        working-directory: ./backend
        run: php bin/console doc:mig:mig --no-interaction -e test

      - name: Exec tests
        working-directory: ./backend
        run: composer tuc
