name: frontend
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  lint-and-tests:
    runs-on: ubuntu-latest

    env:
      DIRECTORY: ./frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install dependencies
        working-directory: ${{ env.DIRECTORY }}
        run: npm ci

      - name: Run format
        working-directory: ${{ env.DIRECTORY }}
        run: npm run format

      - name: Run lint
        working-directory: ${{ env.DIRECTORY }}
        run: npm run lint

      - name: Run tests
        working-directory: ${{ env.DIRECTORY }}
        run: npm run test:cov

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          file: ${{ format('{0}/coverage/clover.xml', env.DIRECTORY) }}
          flags: frontend
          token: ${{ secrets.CODECOV_TOKEN }}
