name: frontend
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Run prettier
        working-directory: ./frontend
        run: npm run format
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run eslint
        working-directory: ./frontend
        run: npm run lint
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run jest
        working-directory: ./frontend
        run: npm run test:cov
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run jest e2e
        working-directory: ./frontend
        run: npm run test:e2e
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
